/**
 * SCRBRD Master Drill Library Data
 * Implements drill taxonomy & metadata spec according to SCRBRD Cricket OS Sections 15 & 16.
 */

import { Drill } from "@/types/drills";

export const MASTER_DRILL_LIBRARY: Drill[] = [
    // Batting Drills
    {
        id: "bat_01",
        sport: "Cricket",
        name: "Drop-and-Run Strike Rotation",
        category: "Batting",
        subcategory: "strike rotation",
        description: "Partner drill focusing on soft hands into the inner ring to complete quick singles.",
        linkedAttributes: ["Strike Rotation", "Running Between Wickets", "Tempo Control"],
        linkedDomains: ["Batting", "Tactical"],
        linkedRoleArchetypes: ["Opener", "Top-order Anchor", "Middle-order Stabiliser"],
        ageSuitability: ["U13", "U15", "U19", "Open"],
        intensity: "Moderate",
        durationMinutes: 20,
        equipment: ["Cones", "Incrediball / Leather Ball", "Target Markers"],
        format: "Pair",
        injuryRestrictions: ["Hamstring Strain", "Lower Back Acute"],
        level: "Foundation",
        coachingObjective: "Develop soft-hand control and early decision making to rotate strike against spin and tight seam.",
        successCriteria: "8 out of 10 successful drop-and-run completions without mid-pitch indecision."
    },
    {
        id: "bat_02",
        sport: "Cricket",
        name: "Spin Footwork & Gap Manipulation",
        category: "Batting",
        subcategory: "playing spin",
        description: "Cone grid scenario where batter must adjust depth in crease or step out to pierce designated field gaps.",
        linkedAttributes: ["Playing Spin", "Footwork", "Gap Finding"],
        linkedDomains: ["Batting", "Tactical"],
        linkedRoleArchetypes: ["Top-order Anchor", "Middle-order Stabiliser", "Wicketkeeper-Batter"],
        ageSuitability: ["U15", "U19", "Open"],
        intensity: "Moderate",
        durationMinutes: 25,
        equipment: ["Sidearm", "Spin Cones", "Nets"],
        format: "Individual",
        injuryRestrictions: ["Ankle Sprain"],
        level: "Intermediate",
        coachingObjective: "Promote decisive footwork forward and back to manipulate spin field placements.",
        successCriteria: "Hit designated 5m target zone 70% of legal deliveries."
    },
    {
        id: "bat_03",
        sport: "Cricket",
        name: "Death-Over Power Hitting & Boundary Range",
        category: "Batting",
        subcategory: "power hitting",
        description: "Targeted full-toss and yorker scenario block focusing on base stability and clean swing plane.",
        linkedAttributes: ["Boundary Hitting", "Shot Range", "Batting Under Pressure"],
        linkedDomains: ["Batting", "Mental"],
        linkedRoleArchetypes: ["Aggressive Middle-order Batter", "Finisher", "Wicketkeeper-Finisher"],
        ageSuitability: ["U15", "U19", "Open"],
        intensity: "High",
        durationMinutes: 30,
        equipment: ["Heavy Balls", "Full Length Net", "Radar Gun"],
        format: "Individual",
        injuryRestrictions: ["Shoulder Impingement", "Wrist Sprain"],
        level: "Advanced",
        coachingObjective: "Maximise exit velocity and boundary execution under simulated 20th over pressure.",
        successCriteria: "Clear 60m boundary line on 5 out of 8 target balls."
    },

    // Bowling Drills
    {
        id: "bowl_01",
        sport: "Cricket",
        name: "Target Grid Line & Length Repeatability",
        category: "Bowling",
        subcategory: "line and length",
        description: "Precision target mat placement at 6-8 meter length with color-coded line channels.",
        linkedAttributes: ["Line Discipline", "Length Discipline", "Control"],
        linkedDomains: ["Bowling"],
        linkedRoleArchetypes: ["New-ball Seamer", "Containment Seamer", "Middle-over Control Bowler"],
        ageSuitability: ["U13", "U15", "U19", "Open"],
        intensity: "Moderate",
        durationMinutes: 30,
        equipment: ["Target Mat", "Cones", "Measuring Tape"],
        format: "Individual",
        injuryRestrictions: ["Lumbar Stress Fracture", "Shin Splints"],
        level: "Foundation",
        coachingObjective: "Build repeatable release mechanics to hit top of off-stump area consistently.",
        successCriteria: "Land 18 out of 24 balls within the 30cm x 30cm target mat."
    },
    {
        id: "bowl_02",
        sport: "Cricket",
        name: "Yorker & Slower Ball Execution Series",
        category: "Bowling",
        subcategory: "death bowling",
        description: "Simulated death over set bowling into shoe-front target block with alternating variation calls.",
        linkedAttributes: ["Death-Over Execution", "Variation Quality", "Repeatability Under Fatigue"],
        linkedDomains: ["Bowling", "Tactical"],
        linkedRoleArchetypes: ["Death Bowler", "Strike Pace Bowler", "Bowling All-rounder"],
        ageSuitability: ["U15", "U19", "Open"],
        intensity: "High",
        durationMinutes: 25,
        equipment: ["Block Hole Target", "Speed Radar"],
        format: "Individual",
        injuryRestrictions: ["Ankle Strain", "Groin Pull"],
        level: "Advanced",
        coachingObjective: "Execute pin-point yorkers and back-of-hand slower balls under high pulse rates.",
        successCriteria: "Hit block hole target 4 times in a 6-ball death over simulation."
    },
    {
        id: "bowl_03",
        sport: "Cricket",
        name: "Flight & Drift Control Grid (Spin)",
        category: "Bowling",
        subcategory: "spin control",
        description: "Revolutions and loop drill over a 2m elevated hurdle to force dip and revs into the surface.",
        linkedAttributes: ["Seam / Swing / Drift / Shape", "Variation Quality", "Release Consistency"],
        linkedDomains: ["Bowling", "Tactical"],
        linkedRoleArchetypes: ["Finger Spinner", "Wrist Spinner"],
        ageSuitability: ["U13", "U15", "U19", "Open"],
        intensity: "Moderate",
        durationMinutes: 25,
        equipment: ["Elevated Hurdle", "RPM Tracker"],
        format: "Individual",
        injuryRestrictions: ["Finger Dislocation"],
        level: "Intermediate",
        coachingObjective: "Impart maximum topspin and drift over the batter's eye line.",
        successCriteria: "Clear hurdle and hit length zone 15/20 deliveries."
    },

    // Fielding Drills
    {
        id: "field_01",
        sport: "Cricket",
        name: "Inner-Ring Pick-and-Hit Pressure Grid",
        category: "Fielding",
        subcategory: "inner-ring pressure fielding",
        description: "High intensity ground fielding circuit requiring one-touch pick-up and direct hit at single stump.",
        linkedAttributes: ["Pick-Up and Release", "Throwing Accuracy", "Reflexes"],
        linkedDomains: ["Fielding", "Physical"],
        linkedRoleArchetypes: ["Fielding Specialist", "Opener", "Aggressive Middle-order Batter"],
        ageSuitability: ["U13", "U15", "U19", "Open"],
        intensity: "High",
        durationMinutes: 20,
        equipment: ["Single Stump", "Katchet Board", "Balls"],
        format: "Group",
        injuryRestrictions: ["Shoulder Dislocation", "Hamstring Strain"],
        level: "Intermediate",
        coachingObjective: "Reduce gather-to-throw transfer time under 1.2 seconds with accurate release.",
        successCriteria: "Hit single stump 5 out of 10 rapid attempts."
    },

    // Wicketkeeping Drills
    {
        id: "keep_01",
        sport: "Cricket",
        name: "Leg-Side Deflection & Fast Stumping Take",
        category: "Wicketkeeping",
        subcategory: "leg-side takes",
        description: "Standing-up keeper drill off spin board handling leg-side deflections and rapid glove-to-stump execution.",
        linkedAttributes: ["Leg-Side Takes", "Stumping Speed", "Footwork to Spin"],
        linkedDomains: ["Wicketkeeping"],
        linkedRoleArchetypes: ["Specialist Wicketkeeper", "Wicketkeeper-Batter", "Wicketkeeper-Finisher"],
        ageSuitability: ["U13", "U15", "U19", "Open"],
        intensity: "Moderate",
        durationMinutes: 25,
        equipment: ["Deflection Board", "Wicketkeeping Gloves", "Stumps"],
        format: "Individual",
        injuryRestrictions: ["Finger Fracture", "Thumb Strain"],
        level: "Advanced",
        coachingObjective: "Maintain low center of gravity and soft hands on blind leg-side nick chances.",
        successCriteria: "Clean collection and stumping execution under 0.8 seconds on 8/10 trials."
    }
];
